import * as fs from 'node:fs';
import * as path from 'node:path';

export type AgentId = 'claude' | 'cursor' | 'copilot';

export interface AgentTarget {
  id: AgentId;
  /** Display name for CLI output. */
  label: string;
  /** Path relative to project root where this agent reads its instructions. */
  outputPath: string;
  /** Heuristic files/directories whose presence implies this agent is in use. */
  presenceHints: string[];
}

export const AGENT_TARGETS: readonly AgentTarget[] = [
  {
    id: 'claude',
    label: 'Claude Code',
    outputPath: 'CLAUDE.md',
    presenceHints: ['CLAUDE.md', '.claude'],
  },
  {
    id: 'cursor',
    label: 'Cursor',
    outputPath: '.cursorrules',
    presenceHints: ['.cursorrules', '.cursor'],
  },
  {
    id: 'copilot',
    label: 'GitHub Copilot',
    outputPath: path.join('.github', 'copilot-instructions.md'),
    presenceHints: [path.join('.github', 'copilot-instructions.md')],
  },
];

export const SOURCE_FILE = 'AGENTS.md';

export const GENERATED_MARKER =
  '<!-- Generated by terso from AGENTS.md. Do not edit; run `terso emit` to update. -->';

export function findTarget(id: AgentId): AgentTarget {
  const t = AGENT_TARGETS.find((t) => t.id === id);
  if (!t) throw new Error(`Unknown agent target: ${id}`);
  return t;
}

/**
 * Detect which agents are likely in use in the project.
 * If no hints are found, returns all known targets — first-run users
 * should get the full set so the CLI is useful out of the box.
 */
export function detectActiveTargets(projectRoot: string): readonly AgentTarget[] {
  const active = AGENT_TARGETS.filter((t) =>
    t.presenceHints.some((hint) => fs.existsSync(path.join(projectRoot, hint))),
  );
  return active.length > 0 ? active : AGENT_TARGETS;
}

/**
 * Render the source content for a given agent target.
 * Format is identical across targets in v1: marker comment + blank line + source body.
 */
export function renderForTarget(_target: AgentTarget, source: string): string {
  const trimmed = source.replace(/\s+$/, '');
  return `${GENERATED_MARKER}\n\n${trimmed}\n`;
}

export function isGenerated(content: string): boolean {
  return content.startsWith(GENERATED_MARKER);
}
