import { Command } from 'commander';
import * as fs from 'node:fs';
import * as path from 'node:path';
import {
  AGENT_TARGETS,
  AgentId,
  AgentTarget,
  GENERATED_MARKER,
  SOURCE_FILE,
  detectActiveTargets,
  findTarget,
  isGenerated,
  renderForTarget,
} from '../lib/agent-targets.js';

interface EmitOptions {
  targets?: string;
  check?: boolean;
  dryRun?: boolean;
  force?: boolean;
  watch?: boolean;
}

export function registerEmitCommand(program: Command): void {
  program
    .command('emit')
    .description(`Compile ${SOURCE_FILE} into per-agent config files at the project root`)
    .option(
      '--targets <list>',
      `comma-separated subset of: ${AGENT_TARGETS.map((t) => t.id).join(', ')}`,
    )
    .option('--check', 'exit non-zero if any target would change (CI gate)')
    .option('--dry-run', 'show what would change without writing')
    .option('--force', 'overwrite existing files even if not generated by terso')
    .option('--watch', 're-emit when AGENTS.md changes (Ctrl+C to stop)')
    .action(async (options: EmitOptions) => {
      try {
        if (options.watch) {
          await runWatch(options, process.cwd());
          return;
        }
        const code = await runEmit(options, process.cwd());
        if (code !== 0) process.exit(code);
      } catch (error) {
        console.error('Emit failed:', error instanceof Error ? error.message : error);
        process.exit(1);
      }
    });
}

async function runWatch(options: EmitOptions, projectRoot: string): Promise<void> {
  const sourcePath = path.join(projectRoot, SOURCE_FILE);
  const watchOptions: EmitOptions = { ...options, watch: false };

  console.log(`Watching ${SOURCE_FILE} (Ctrl+C to stop)`);
  await runEmit(watchOptions, projectRoot);

  let shuttingDown = false;
  const shutdown = () => {
    if (shuttingDown) return;
    shuttingDown = true;
    fs.unwatchFile(sourcePath);
    console.log('\nStopped.');
    process.exit(0);
  };
  process.on('SIGINT', shutdown);
  process.on('SIGTERM', shutdown);

  // 500ms polling — matches existing watch.ts pattern, stable across editors that
  // do rename-on-save (common on macOS) which break fs.watch on some platforms.
  fs.watchFile(sourcePath, { interval: 500 }, async (curr, prev) => {
    if (curr.mtimeMs === prev.mtimeMs) return;
    if (!fs.existsSync(sourcePath)) {
      console.error(`${SOURCE_FILE} was removed.`);
      return;
    }
    console.log(`\n${SOURCE_FILE} changed — re-emitting...`);
    try {
      await runEmit(watchOptions, projectRoot);
    } catch (error) {
      console.error('Re-emit failed:', error instanceof Error ? error.message : error);
    }
  });
}

interface PlannedWrite {
  target: AgentTarget;
  absPath: string;
  rendered: string;
  status: 'create' | 'update' | 'unchanged' | 'blocked';
  reason?: string;
}

export async function runEmit(options: EmitOptions, projectRoot: string): Promise<number> {
  const sourcePath = path.join(projectRoot, SOURCE_FILE);

  if (!fs.existsSync(sourcePath)) {
    console.error(
      `${SOURCE_FILE} not found at project root. Create it with your shared agent instructions first.`,
    );
    return 1;
  }

  const source = fs.readFileSync(sourcePath, 'utf-8');

  let targets: readonly AgentTarget[];
  try {
    targets = resolveTargets(options.targets, projectRoot);
  } catch (error) {
    console.error(error instanceof Error ? error.message : String(error));
    return 1;
  }

  if (targets.length === 0) {
    console.error('No targets selected.');
    return 1;
  }

  const plans: PlannedWrite[] = targets.map((target) => planWrite(target, source, projectRoot, options.force === true));

  const blocked = plans.filter((p) => p.status === 'blocked');
  const changes = plans.filter((p) => p.status === 'create' || p.status === 'update');
  const unchanged = plans.filter((p) => p.status === 'unchanged');

  for (const p of plans) {
    const rel = path.relative(projectRoot, p.absPath);
    if (p.status === 'blocked') {
      console.error(`  blocked  ${rel}  (${p.reason})`);
    } else if (p.status === 'create') {
      console.log(`  create   ${rel}`);
    } else if (p.status === 'update') {
      console.log(`  update   ${rel}`);
    } else {
      console.log(`  ok       ${rel}`);
    }
  }

  if (blocked.length > 0) {
    console.error(
      `\n${blocked.length} file(s) blocked. Use --force to overwrite, or delete the file first.`,
    );
    return 1;
  }

  if (options.check) {
    if (changes.length > 0) {
      console.error(`\n${changes.length} file(s) out of date. Run \`terso emit\`.`);
      return 1;
    }
    console.log(`\nAll ${unchanged.length} target(s) up to date.`);
    return 0;
  }

  if (options.dryRun) {
    console.log(`\nDry run — ${changes.length} file(s) would change, ${unchanged.length} unchanged.`);
    return 0;
  }

  for (const p of changes) {
    fs.mkdirSync(path.dirname(p.absPath), { recursive: true });
    fs.writeFileSync(p.absPath, p.rendered, 'utf-8');
  }

  console.log(`\nEmitted ${changes.length} file(s) from ${SOURCE_FILE} (${unchanged.length} unchanged).`);
  return 0;
}

function resolveTargets(spec: string | undefined, projectRoot: string): readonly AgentTarget[] {
  if (!spec) return detectActiveTargets(projectRoot);

  const ids = spec
    .split(',')
    .map((s) => s.trim())
    .filter(Boolean);

  return ids.map((id) => findTarget(id as AgentId));
}

function planWrite(
  target: AgentTarget,
  source: string,
  projectRoot: string,
  force: boolean,
): PlannedWrite {
  const absPath = path.join(projectRoot, target.outputPath);
  const rendered = renderForTarget(target, source);

  if (!fs.existsSync(absPath)) {
    return { target, absPath, rendered, status: 'create' };
  }

  const existing = fs.readFileSync(absPath, 'utf-8');

  if (existing === rendered) {
    return { target, absPath, rendered, status: 'unchanged' };
  }

  if (!isGenerated(existing) && !force) {
    return {
      target,
      absPath,
      rendered,
      status: 'blocked',
      reason: 'file exists and is not marked as generated by terso',
    };
  }

  return { target, absPath, rendered, status: 'update' };
}

export const _internal = { GENERATED_MARKER };
