import { Command } from 'commander';
import * as fs from 'node:fs';
import * as path from 'node:path';
import {
  AGENT_TARGETS,
  AgentTarget,
  GENERATED_MARKER,
  SOURCE_FILE,
  detectActiveTargets,
  findTarget,
  isGenerated,
  renderForTarget,
} from '../lib/agent-targets.js';

interface EmitOptions {
  targets?: string;
  check?: boolean;
  dryRun?: boolean;
  force?: boolean;
  watch?: boolean;
  prune?: boolean;
}

export function registerEmitCommand(program: Command): void {
  program
    .command('emit')
    .description(`Compile ${SOURCE_FILE} into per-agent config files at the project root`)
    .option(
      '--targets <list>',
      `comma-separated subset of: ${AGENT_TARGETS.map((t) => t.id).join(', ')}`,
    )
    .option(
      '--check',
      'CI gate. Exit 0 if everything is up to date, 1 if any target needs to change, 2 on error.',
    )
    .option('--dry-run', 'show what would change without writing')
    .option('--force', 'overwrite existing files even if not generated by terso')
    .option('--watch', 're-emit when AGENTS.md changes (Ctrl+C to stop)')
    .option('--prune', 'delete terso-generated files for targets no longer active')
    .action(async (options: EmitOptions) => {
      try {
        if (options.watch) {
          await runWatch(options, process.cwd());
          return;
        }
        const code = await runEmit(options, process.cwd());
        if (code !== 0) process.exit(code);
      } catch (error) {
        console.error('Emit failed:', error instanceof Error ? error.message : error);
        // Exit 2 on uncaught error; emit --check reserves 0 (clean) and 1 (drift).
        process.exit(2);
      }
    });
}

async function runWatch(options: EmitOptions, projectRoot: string): Promise<void> {
  const sourcePath = path.join(projectRoot, SOURCE_FILE);
  const watchOptions: EmitOptions = { ...options, watch: false };

  console.log(`Watching ${SOURCE_FILE} (Ctrl+C to stop)`);
  await runEmit(watchOptions, projectRoot);

  let shuttingDown = false;
  const shutdown = () => {
    if (shuttingDown) return;
    shuttingDown = true;
    fs.unwatchFile(sourcePath);
    console.log('\nStopped.');
    process.exit(0);
  };
  process.on('SIGINT', shutdown);
  process.on('SIGTERM', shutdown);

  // 500ms polling — matches existing watch.ts pattern, stable across editors that
  // do rename-on-save (common on macOS) which break fs.watch on some platforms.
  fs.watchFile(sourcePath, { interval: 500 }, async (curr, prev) => {
    if (curr.mtimeMs === prev.mtimeMs) return;
    if (!fs.existsSync(sourcePath)) {
      console.error(`${SOURCE_FILE} was removed.`);
      return;
    }
    console.log(`\n${SOURCE_FILE} changed — re-emitting...`);
    try {
      await runEmit(watchOptions, projectRoot);
    } catch (error) {
      console.error('Re-emit failed:', error instanceof Error ? error.message : error);
    }
  });
}

interface PlannedWrite {
  target: AgentTarget;
  absPath: string;
  rendered: string;
  status: 'create' | 'update' | 'unchanged' | 'blocked';
  reason?: string;
}

export async function runEmit(options: EmitOptions, projectRoot: string): Promise<number> {
  const sourcePath = path.join(projectRoot, SOURCE_FILE);

  if (!fs.existsSync(sourcePath)) {
    console.error(
      `${SOURCE_FILE} not found at project root. Create it with your shared agent instructions first.`,
    );
    return 2;
  }

  if (!fs.statSync(sourcePath).isFile()) {
    console.error(`${SOURCE_FILE} exists but is not a file (is it a directory?). Expected a Markdown file.`);
    return 2;
  }

  const source = fs.readFileSync(sourcePath, 'utf-8');

  if (source.trim().length === 0) {
    console.error(`warning: ${SOURCE_FILE} is empty or whitespace-only — generated files will have no rules.`);
  }

  let targets: readonly AgentTarget[];
  try {
    targets = resolveTargets(options.targets, projectRoot);
  } catch (error) {
    console.error(error instanceof Error ? error.message : String(error));
    return 2;
  }

  if (targets.length === 0) {
    console.error('No targets selected.');
    return 2;
  }

  const plans: PlannedWrite[] = targets.map((target) => planWrite(target, source, projectRoot, options.force === true));

  const blocked = plans.filter((p) => p.status === 'blocked');
  const changes = plans.filter((p) => p.status === 'create' || p.status === 'update');
  const unchanged = plans.filter((p) => p.status === 'unchanged');

  const checking = options.check === true;
  for (const p of plans) {
    const rel = path.relative(projectRoot, p.absPath);
    if (p.status === 'blocked') {
      console.error(`  blocked  ${rel}  (${p.reason})`);
    } else if (p.status === 'create') {
      console.log(`  ${checking ? 'drift    ' : 'create   '}${rel}`);
    } else if (p.status === 'update') {
      console.log(`  ${checking ? 'drift    ' : 'update   '}${rel}`);
    } else {
      console.log(`  ok       ${rel}`);
    }
  }

  if (blocked.length > 0) {
    console.error(
      `\n${blocked.length} file(s) blocked. Use --force to overwrite, or delete the file first.`,
    );
    return 2;
  }

  if (options.check) {
    if (changes.length > 0) {
      console.error(`\n${changes.length} file(s) out of date. Run \`terso emit\`.`);
      return 1;
    }
    console.log(`\nAll ${unchanged.length} target(s) up to date.`);
    return 0;
  }

  if (options.dryRun) {
    console.log(`\nDry run — ${changes.length} file(s) would change, ${unchanged.length} unchanged.`);
    return 0;
  }

  for (const p of changes) {
    try {
      fs.mkdirSync(path.dirname(p.absPath), { recursive: true });
      fs.writeFileSync(p.absPath, p.rendered, 'utf-8');
    } catch (err) {
      const rel = path.relative(projectRoot, p.absPath);
      console.error(`Failed to write ${rel}: ${err instanceof Error ? err.message : err}`);
      return 2;
    }
  }

  // Orphan detection: a marker-stamped file whose target is not in the active set.
  const activePaths = new Set(targets.map((t) => path.join(projectRoot, t.outputPath)));
  const orphans = AGENT_TARGETS
    .map((t) => path.join(projectRoot, t.outputPath))
    .filter((abs) => !activePaths.has(abs) && fs.existsSync(abs))
    .filter((abs) => isGenerated(fs.readFileSync(abs, 'utf-8')));

  if (orphans.length > 0) {
    if (options.prune) {
      for (const abs of orphans) {
        fs.rmSync(abs);
        console.log(`  prune    ${path.relative(projectRoot, abs)}`);
      }
    } else {
      for (const abs of orphans) {
        console.error(
          `note: ${path.relative(projectRoot, abs)} is generated but no longer an active target. Run \`terso emit --prune\` to remove it.`,
        );
      }
    }
  }

  console.log(`\nEmitted ${changes.length} file(s) from ${SOURCE_FILE} (${unchanged.length} unchanged).`);
  return 0;
}

function resolveTargets(spec: string | undefined, projectRoot: string): readonly AgentTarget[] {
  // 1. Explicit --targets flag always wins.
  if (spec) {
    const ids = spec.split(',').map((s) => s.trim()).filter(Boolean);
    return ids.map((id) => findTarget(id));
  }

  // 2. Pinned list in .terso/project.json wins over detection.
  const pinned = readPinnedTargets(projectRoot);
  if (pinned && pinned.length > 0) {
    return pinned.map((id) => findTarget(id));
  }

  // 3. Fall back to detection — but never silently. Tell the user what was
  //    detected and what was skipped so missing agents are visible.
  const detected = detectActiveTargets(projectRoot);
  const detectedIds = new Set(detected.map((t) => t.id));
  const skipped = AGENT_TARGETS.filter((t) => !detectedIds.has(t.id)).map((t) => t.id);
  if (skipped.length > 0) {
    console.error(
      `note: emitting to detected targets [${[...detectedIds].join(', ')}]; ` +
        `skipping [${skipped.join(', ')}]. Run \`terso init\` or use --targets to pin the full set.`,
    );
  }
  return detected;
}

function readPinnedTargets(projectRoot: string): string[] | null {
  try {
    const cfgPath = path.join(projectRoot, '.terso', 'project.json');
    if (!fs.existsSync(cfgPath)) return null;
    const cfg = JSON.parse(fs.readFileSync(cfgPath, 'utf-8'));
    return Array.isArray(cfg.targets) ? cfg.targets : null;
  } catch {
    return null; // malformed config — fall through to detection
  }
}

function planWrite(
  target: AgentTarget,
  source: string,
  projectRoot: string,
  force: boolean,
): PlannedWrite {
  const absPath = path.join(projectRoot, target.outputPath);
  const rendered = renderForTarget(target, source);

  if (!fs.existsSync(absPath)) {
    return { target, absPath, rendered, status: 'create' };
  }

  const existing = fs.readFileSync(absPath, 'utf-8');

  if (existing === rendered) {
    return { target, absPath, rendered, status: 'unchanged' };
  }

  if (!isGenerated(existing) && !force) {
    return {
      target,
      absPath,
      rendered,
      status: 'blocked',
      reason: 'file exists and is not marked as generated by terso',
    };
  }

  return { target, absPath, rendered, status: 'update' };
}

export const _internal = { GENERATED_MARKER };
